language: php

php:
  - 7.1
  - 7.2

sudo: false

services:
  - mysql

env:
  matrix:
    - SHOPWARE_VERSION="5.2"
    - SHOPWARE_VERSION="5.3"
    - SHOPWARE_VERSION="5.4"
    - SHOPWARE_VERSION="5.5"
  global:
  - PLUGIN_NAME=FroshIonCubeChecker
  - SHOPWARE_DIRECTORY="${HOME}/shopware"
  - PLUGIN_DIRECTORY="${SHOPWARE_DIRECTORY}/custom/plugins"

cache:
  directories:
    - ${HOME}/.composer/cache/files

install:
  - composer install

before_script:
  - mysql -e 'CREATE DATABASE shopware;'
  - if [[ "$(php --version | grep -cim1 xdebug)" -ge 1 ]]; then phpenv config-rm xdebug.ini; fi
  - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}
  - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
  - mv ${TRAVIS_BUILD_DIR} ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:refresh
  - php ${HOME}/shopware/bin/console sw:plugin:install ${PLUGIN_NAME}
  - php ${HOME}/shopware/bin/console sw:plugin:activate ${PLUGIN_NAME}
  - cd ${PLUGIN_DIRECTORY}/${PLUGIN_NAME}

script:
  -

after_success:
  - ./build.sh $TRAVIS_TAG

stages:
  - name: Store-Check
    if: tag IS blank AND env(PLUGIN_ID) IS present AND type != pull_request
  - name: Store-Sync
    if: branch = master AND env(PLUGIN_ID) IS present AND type != pull_request
  - name: Store-Deploy
    if: tag IS present

jobs:
  include:
    - stage: Store-Check
      php: 7.3
      before_script: skip
      install:
        - ./build.sh "master"
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.0/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:validate ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip
    - stage: Store-Sync
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.0/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:update ${TRAVIS_BUILD_DIR}/Resources/store
    - stage: Store-Deploy
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/0.1.0/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar
      script:
        - ./build.sh
        - php frosh-plugin-upload.phar plugin:upload ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip

deploy:
  provider: releases
  api_key:
    secure: 2+GiCW139cIlQAOctzE1P3RSxV+Z0LJLLNF5Gqv3UItP1OqI8nhsLTWeSSKcHOK3Mwx4PXZf66UCQ5YU5uIjA2tuatxpSv6FltIwRDRkXrgRqCtlBWP6h5tV60In/UA+TlCWKJncKqg/cki/m//zhm09GZZx9b9vC+H11RHU3IqTguiziH1rEj4t4ihqYKAJCO3C7q3xfMCme6/fSG8cts9bzzBqqqPgRBk3q8Bda000sBjwIFEkmouEjebnWrRpQR3WejeGsCNRI6r5+XmiGhd248LtOqRgpib30RyJy7VxSfzsGJ6bVgqGcMyaNeCZ6Nn+LyiP4kuZN1Wsj89VxTKM1eYoEg+44iOpl5jbhz1vvcXincVsu8riKPkc3HmkXU2UvTc5u+MUSaOt1CZ4fGO6kx4Ee2UCKj8RsnRUWYhmDvnktGxoWpW/Q5q7EQ2eKC1I5t6ocAgwBFRELiXYUuzOfJme1zp0NkVJQMomcWKLKzsqdSOKrzfYx0d2DWZqT87jQOXn+9N0DbrMEH7rjByAjZuY00hR3itOoKnXOKXQdsV51UWZ2YSCmZwwkgtMPJFTZgfLAZ7DIqU3FKFUScDbv1ODThkjz/Ayd3956p5cwzGULFdJ1/SWREtdHWhwD1ovhm3TVHgE9LnfamIiF+c15XcAW+io8SQOhuNDXoo=
  file_glob: true
  file: $PLUGIN_NAME*.zip
  skip_cleanup: true
  on:
    repo: FriendsOfShopware/FroshIonCubeChecker
    tags: true
